
version: '3.7'

services:

  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql-setup/init.sql:/data/application/init.sql
      - ./mysql-data:/var/lib/mysql
    #ports:
      #- "3311:3306"
    container_name: mysql-container1



  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-container1
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8089:80"
    container_name: phpmyadmin-container1
  
  api:
    build: ./backend-server
    restart: always
    #ports:
      #- "3002:3002" # Expose API port
    container_name: backend-container1
    environment: # Set ENV vars
     - NODE_ENV=local
     - PORT=3002
    volumes: # Attach local book data directory
      - ./process_files:/process_files

  monitoring-server:
    build: ./python-server
    container_name: python-container1


  angular-app:
    build: ./frontend-server
    #ports:
      #- "4202:4202"
    container_name: frontend-container1


  nginx:
    depends_on:
      - angular-app
      - api
    restart: always
    build: ./nginx-server
    ports:
      - "3050:80"
    container_name: nginx-container

      



